cyberjunk/meridian59-dotnet

Meridian59.Bot.Spell/SpellBotClient.cs, Meridian59.Bot.Spell/SpellBotConfig.cs, Meridian59.Bot.Spell/Tasks/BotTaskCast.cs, Meridian59.Bot.Spell/configuration.xml, Meridian59/Common/Constants/Constants.cs
Added "cap" attribute to task "cast".
Added XMLVALUE "self" ad value for "cast" Tasks "target" attribute.
-using selftarget forced "where" to room.
-leaving cap empty/0 will work like cap="99"
-cap above 99 will spin endless
-added .ToLower() on AMLVALUE check to ensure compability for diffenet write cases
=> Spell bot attr cap

Meridian59/Client/BaseClient.cs
I think this is right...
SendUserCommandGuildInvite should make a new UserCommandGuildInvite instead of UserCommandGuildVote.
=> Fix UserCommandGuildInvite in BaseClient.cs

Meridian59/Files/ROO/RooFile.cs, Meridian59/Files/ROO/RooGrids.cs
Version 15 rooms no longer include the server movement flags/grids, so don't try to load them.
=> Prevent room grid loading on roo version >= 15.

Meridian59/Common/Config.cs
After loading the connection profiles from configuration.xml, perform a check for each server and add it if missing from config file.
This works for me locally and I'm able to log into the new profiles, but not sure if this is the correct solution or if there's something better.
=> Add any missing servers to dropdown/configuration.

Meridian59.Ogre.Client/OgreClient.cpp, Meridian59/Common/Constants/FileExtensions.cs, Meridian59/Common/Constants/ResourceStrings.cs, Meridian59/Data/Models/PlayMusic.cs, Meridian59/Data/Models/PlaySound.cs, Meridian59/Files/ResourceManager.cs
Ogre will now convert string names for music resources (which may have extension .mp3/.wav/.mid) to .ogg. I'm not sure what else I need to change here, as this enables both sound and music to play on 104 (resources .wav/.mp3) and 106 (resources .ogg).
Also not sure which is the best way for me to submit the .ogg files - should I make a separate PR to the meridian59-resources repo, or upload the files somewhere for you to add them?
=> Modify Ogre client to use OGG format for sound/music.

Meridian59.Bot.IRC/IRCBotClient.cs, Meridian59.Bot.IRC/IRCBotConfig.cs, Meridian59.Bot.IRC/IRCChatStyle.cs, Meridian59.Bot.IRC/Meridian59.Bot.IRC.csproj, Meridian59.Bot.IRC/Properties/AssemblyInfo.cs, Meridian59.Bot.IRC/RelayConfig.cs, Meridian59.Bot.IRC/configuration.xml, Meridian59/Common/Util.cs
This includes #105 as both PRs are being used in production and edit the same code. I can rebase etc. if necessary or make modifications here.
Two IRC bots in the same IRC channel (and on different servers) will be able to output the broadcasts and deaths from one server to another. E.g. if Server103Chat echoes a broadcast from server 103, Server105Chat can convert it back to a m59-compatible string and broadcast it on 105, using the dm gqemote command to avoid feedback loops.
For a bot to echo other bots' text, it will need to list that bot's name and a banner (for when the text hits the bots own server) in configuration.xml.
=> Add ability for IRC bots to echo each other's output to their own server.

Meridian59.Ogre.Client/Constants.h, Meridian59.Ogre.Client/ControllerUI.cpp, Meridian59.Ogre.Client/ControllerUI.h, Meridian59.Ogre.Client/Meridian59.Ogre.Client.vcxproj, Meridian59.Ogre.Client/Meridian59.Ogre.Client.vcxproj.filters, Meridian59.Ogre.Client/OgreClient.cpp, Meridian59.Ogre.Client/OgreClient.h, Meridian59.Ogre.Client/UIDownloadBar.cpp, Meridian59/Client/BaseClient.cs, Meridian59/Common/Events/IntegerEvent.cs, Meridian59/Meridian59.csproj, Meridian59/Protocol/DownloadHandler.cs
This isn't quite finished yet - it works (can patch Ogre from 106 using this), but most of the code is in BaseClient.cs when it should probably be elsewhere and there's some hardcoded strings that need to change. Making the PR early because I need a bit of guidance on how you would like this code organised.
I think the message from the server (ClientPatchMessage.cs) and the info itself (ClientPatchInfo.cs) are probably okay, but I'm unsure about where the classes for the JSON patch file (patchinfo.txt) should be (the classes PatchFile and PatchFileList at the end of BaseClient.cs).
Also not sure if the way I'm handling the download form (ClientPatchForm.cs) or WebClient are ideal.
=> In-client update process for Ogre client (work in progress).

Meridian59/Protocol/DownloadHandler.cs
GetExecutingAssembly() returns Meridian59.dll, GetEntryAssembly() returns the calling program (the client exe).
=> Fix opening of Ogre client after an update.

Meridian59.Ogre.Client/OgreClient.h
The new client installers contain only enough files to run Ogre and connect to a server, and rely on the in-client update feature to download the rest of the files. To ensure this happens, the installers will contain the first version of Ogre client that has this feature (version 9005) and the server will need to have a lower version set (at least 9006) to always force an update for these clients.
=> Increment Ogre client version to accommodate installers.

Meridian59.Ogre.Client/OgreClient.h, Meridian59/Client/BaseClient.cs, Meridian59/Common/Hash128Bit.cs, Meridian59/Common/MeridianMD5.cs, Meridian59/Files/ResourceManager.cs, Meridian59/Meridian59.csproj, Meridian59/Protocol/GameMessages/GameMode/ChangePasswordMessage.cs, Meridian59/Protocol/GameMessages/LoginMode/LoginMessage.cs
The rsb file is hashed on loading and the hash sent to the server during login. The server will trigger a client update if the rsb hash does not match the server's loaded one.
This is the .NET implementation of https://github.com/OpenMeridian105/Meridian59/pull/172. If this approach is correct I'd probably move the file hash function to Util.cs in case we need it elsewhere.
=> Hash rsb file on login, send hash to server.

Meridian59/Files/ROO/RooWall.cs
The walls causing issues are ~0.002 out, use 0.01 as epsilon check to be safe.
=> Change epsilon value in GetVertexData.

Meridian59.Ogre.Client/MiniMapCEGUI.cpp, Meridian59.Ogre.Client/MiniMapCEGUI.h, Meridian59.Ogre.Client/OgreClient.h, Meridian59/Data/Models/ObjectFlags.cs, Meridian59/Drawing2D/MiniMap.cs
The next 105/112 update will introduce a new minimap dot, for players flagged as non-combatants (opt-out of PvP, see OpenMeridian105/Meridian59#237). Shows up as a white dot on minimap.
Fixed an issue where tempsafe and the new minimap dot wouldn't be displayed as the object flag check called in MiniMapCEGUI.cpp was IsPlayer versus the minimap flag IsMinimapPlayer.
Incremented Ogre client version.
=> Add new minimap dot for non-pvp flagged players.

Meridian59.AdminUI/Viewers/InventoryObjectView.Designer.cs, Meridian59.AdminUI/Viewers/InventoryObjectView.resx, Meridian59.AdminUI/Viewers/ObjectBaseView.Designer.cs, Meridian59.AdminUI/Viewers/ObjectBaseView.resx, Meridian59.AdminUI/Viewers/RoomObjectsView.Designer.cs, Meridian59.AdminUI/Viewers/RoomObjectsView.resx, Meridian59.AdminUI/Viewers/SpellsView.Designer.cs, Meridian59.AdminUI/Viewers/SpellsView.resx, Meridian59.Ogre.Client/OgreClient.cpp, Meridian59.Ogre.Client/RemoteNode.cpp, Meridian59.Ogre.Client/Util.h, Meridian59/Common/Interfaces/ILightOwner.cs, Meridian59/Data/Models/InventoryObject.cs, Meridian59/Data/Models/LightFlags.cs, Meridian59/Data/Models/LightingInfo.cs, Meridian59/Data/Models/ObjectBase.cs, Meridian59/Data/Models/ObjectUpdate.cs, Meridian59/Data/Models/PlayerOverlay.cs, Meridian59/Data/Models/Projectile.cs, Meridian59/Data/Models/RoomObject.cs, Meridian59/Data/Models/SpellObject.cs, Meridian59/Data/Models/TradeOfferObject.cs, Meridian59/Meridian59.csproj
Change LightFlags from ushort to its own type, add LightingInfo class to hold the new LightFlags plus the light intensity and color (still byte/ushort respectively).
Replicate classic client's highlight effect for signs by lowering the range on these lights to 12% of normal.
=> Add LightingInfo and LightFlags classes, add highlighting light effect used on signs.

Meridian59.AdminUI/Viewers/InventoryObjectView.Designer.cs, Meridian59.AdminUI/Viewers/InventoryObjectView.resx, Meridian59.AdminUI/Viewers/ObjectBaseView.Designer.cs, Meridian59.AdminUI/Viewers/ObjectBaseView.resx, Meridian59.AdminUI/Viewers/RoomObjectsView.Designer.cs, Meridian59.AdminUI/Viewers/RoomObjectsView.resx, Meridian59.AdminUI/Viewers/SpellsView.Designer.cs, Meridian59.AdminUI/Viewers/SpellsView.resx, Meridian59.Ogre.Client/OgreClient.cpp, Meridian59.Ogre.Client/RemoteNode.cpp, Meridian59.Ogre.Client/Util.h, Meridian59/Common/Interfaces/ILightOwner.cs, Meridian59/Data/Models/InventoryObject.cs, Meridian59/Data/Models/LightingInfo.cs, Meridian59/Data/Models/ObjectBase.cs, Meridian59/Data/Models/ObjectUpdate.cs, Meridian59/Data/Models/PlayerOverlay.cs, Meridian59/Data/Models/Projectile.cs, Meridian59/Data/Models/RoomObject.cs, Meridian59/Data/Models/SpellObject.cs, Meridian59/Data/Models/TradeOfferObject.cs, Meridian59/Meridian59.csproj
Continued from #119
Add LightingInfo class to hold all the lighting information - flags, intensity and color.
Replicate classic client's highlight effect for signs by lowering the range on these lights to 12% of normal.
Adjust admin UI to display the new LightingInfo property field combining all 3 lighting properties into a string.
=> Add LightingInfo class, add highlighting light effect used on signs.

Meridian59/Client/BaseClient.cs, Resources/ui/layouts/Meridian59.layout
Unless a lootable item is selected, the loot window will now open if the
loot button is pressed and close again upon a second press. If a
lootable item is selected, it will be looted without loot window toggle
instead. If the modifier key is held, everything will be looted without
toggle as before.
=> Enhanced looting functionality

Meridian59/Client/BaseClient.cs, Meridian59/Data/Models/ChatCommand/ChatCommand.cs, Meridian59/Data/Models/ChatCommand/ChatCommandAppeal.cs, Meridian59/Data/Models/ChatCommand/ChatCommandBalance.cs, Meridian59/Data/Models/UserCommand/UserCommand.cs, Meridian59/Data/Models/UserCommand/UserCommandAppeal.cs, Meridian59/Data/Models/UserCommand/UserCommandBalance.cs, Meridian59/Data/Models/UserCommand/UserCommandGuildCreate.cs, Meridian59/Meridian59.csproj
Added missing 'balance' and 'appeal' chat commands/user commands.
Before this gets merged, I was wondering if I should add the 'time' chat command that gets a printout of the time from the server. I know Ogre has its own game time in the titlebar and this should be in sync outside modified server time (i.e. testing, live servers are in sync) so this would mainly be for completeness.
Also fixed secret guild creation (wasn't working due to typo).
=> Add 'balance' and 'appeal' chat commands, fix secret guild creation.

Meridian59.Bot.IRC/IRCBotClient.cs, Meridian59.Bot.IRC/Properties/AssemblyInfo.cs, Meridian59.Bot.IRC/WINSERVICE.txt
We can gate unwanted DM commands behind DM flags on the server now, so
the help bot can still perform useful DM commands (dm gqemote for system
messages etc). Increased assembly version and also fixed a typo in the
bot service instructions.
=> Remove 'dm' cmd restriction on IRC bot.

Meridian59/Client/BaseClient.cs, Meridian59/Common/Enums/UserCommandType.cs, Meridian59/Data/Models/ChatCommand/ChatCommand.cs, Meridian59/Data/Models/ChatCommand/ChatCommandTime.cs, Meridian59/Data/Models/UserCommand/UserCommand.cs, Meridian59/Data/Models/UserCommand/UserCommandTime.cs, Meridian59/Meridian59.csproj
I commented on this one in #204 but don't think you saw it, this command is partly not needed because Ogre displays the game time but 'time' can also be used to get the day and year, e.g.
```
The time in Meridian is 9:00.  It is the 224th day of the year 14.
```
=> Add 'time' chat/user command.

Meridian59.Bot.Shop/configuration.xml, Meridian59.Bot.Spell/configuration.xml, Meridian59.Ogre.Client/OgreClient.h, Meridian59.Ogre.Client/configuration.template.xml, Meridian59/Common/Config.cs, Meridian59/Data/Models/ConnectionInfo.cs
Servers 112 and 200 are moving to a new domain, changing from arantis.eu to meridian59.de. Updated the connection profiles and also added a check for the old host during connection profile load so that we can update existing clients without moving 112/200 in their connection list.
Incremented the Ogre client version since we will need players to update so they have the new domain.
Also added some #if OPENMERIDIAN checks to match the existing one with the 103/104 connection profiles.
=> Add new 112/200 domain, increment Ogre client vers.

Meridian59.Ogre.Client/Constants.h, Meridian59.Ogre.Client/ControllerUI.h, Meridian59.Ogre.Client/OgreClient.cpp, Meridian59.Ogre.Client/UIConfirmPopup.cpp, Meridian59.Ogre.Client/UIGuild.cpp, Resources/ui/layouts/Meridian59.layout
Guild UI was missing an 'Abandon guildhall' button to drop the guild's hall. Added this, and also added text which is displayed instead of the guildhall options if the user has no hall.
If the user shouldn't have the tabs for GuildMaster and Shield, remove them from being displayed. Replace them if the user then tries to access the Guild menu as a guildmaster. In CEGUI there's no actual way to do this save for removing and replacing the tab windows from the TabControl (as per http://cegui.org.uk/forum/viewtopic.php?t=3736 and http://cegui.org.uk/forum/viewtopic.php?f=10&p=35580).
Make exile, renounce, disband and abandon hall all require an additional confirmation before carrying out the action. Confirm dialog box prevents interacting with other UI elements until the box is addressed.
One …
=> Add missing Guild UI features, confirm dialog boxes for guild UI actions.

Meridian59/Common/MeridianDate.cs, Meridian59/Data/Models/Mail.cs
Convert any old mail timestamps (on load) from offset time to the proper unix epoch time and save the mail after conversion.
Change the OFFSET value to 0 as unix time with no offset will be used for mail/news.
TODO: wondering where in the 'mail received' process I should set IsTimestampUpdated to true (with the assumption that any mail received has a unix timestamp). One way to verify the timestamp is valid, if we didn't want to assume it was, is to check against MAX_KOD_INT as any timestamp from the server larger than that would be a valid updated one (or from the early 1970s but I don't think we need to account for that). We could get around needing an IsTimestampUpdated field by performing the same check on mails when fixing (e.g. lower than MAX_KOD_INT? add offset and save).
=> Convert old mail timestamps to unix time.

Meridian59.Bot.IRC/IRCChatStyle.cs, Meridian59/Data/Models/ChatCommand/ChatStyle.cs, Meridian59/Data/Models/ServerString.cs
Added strikethrough and hyperlink text styles to corelib and IRCBot.
Not all IRC clients support strikethrough, but it does work on IRCCloud (web-only, not app). None appear to support link text activated by character, instead handling links their own way (i.e. the bot probably shouldn't try to add any).
CEGUI doesn't support either style yet. I was able to get a crude underline effect working in CEGUI (would be good but doesn't quite line up italics with non-italics underline) however I'm not sure if we want to diverge from CEGUI upstream at all.
=> Add new chat styles to corelib/ircbot.

Meridian59/Data/Models/ServerString.cs
Kod resource strings use %% to display a literal % in text, so one % has
to be removed or a literal %% will be displayed. Handled as a variable
that removes the % at index.
=> Fix handling of %% in kod resource strings.

Meridian59.Ogre.Client/ControllerUI.h, Meridian59.Ogre.Client/Language.cpp, Meridian59.Ogre.Client/Language.h, Meridian59.Ogre.Client/UIAvatarCreateWizard.cpp, Meridian59/Common/Enums/CharInfoNotOkError.cs, Meridian59/Data/DataController.cs, Meridian59/Data/Models/CharCreationInfo.cs, Meridian59/Meridian59.csproj, Meridian59/Protocol/GameMessages/GameMode/CharInfoNotOkMessage.cs, Resources/ui/layouts/Meridian59.layout
Handle the new CharInfoNotOk error codes returned by the server to better describe char creation errors.
Changed the error size to byte from the previous code I had up.
Not sure if there is a way to skip the switch statement in UIAvatarCreateWizard.cpp where it converts from the CharInfoNotOkError enum to the language enum, or if this way is preferred for safety.
Also the OK dialog box's Text field isn't big enough to hold these error messages, I'm still looking for a good way to adjust this box (and possibly move the OK button depending on size) without making the defaults huge or adding a new box to the .layout file. This topic http://cegui.org.uk/forum/viewtopic.php?f=5&t=7101 implies there might not be an easy CEGUI method to do so.
=> Add CharInfoNotOk improvements, Confirm dialog box adjustment for more text.

Meridian59/Data/Models/WallAnimationChange.cs, Meridian59/Files/ROO/RooFile.cs, Meridian59/Files/ROO/RooSideDef.cs, Meridian59/Meridian59.csproj, Meridian59/Protocol/GameMessages/GameMode/WallAnimateMessage.cs
Changing wall animation to ANIMATE_NONE should stop scrolling, so needs to set sidedef ScrollSpeed to 0.
Moved some sidedef-specific code from RooFile to RooSideDef, and moved wall animation change details out of WallAnimateMessage properties and into a WallAnimationChange class (mirroring SectorChange/SectorChangeMessage).
Note - this doesn't stop water scrolling entirely since some water motion seems controlled by the water shader, however it works on normal textures.
=> Fix scrolling speed on wall animation change.

Meridian59/Common/MeridianDate.cs
The servers will be using UTC hours and minutes to set game time, so
that every even (UTC) hour is midnight. This is more easily reproducible
by the clients and means daylight savings doesn't need to be handled.
=> Remove daylight savings from GetMeridianTime().

Meridian59.Bot.IRC/IRCBotClient.cs, Meridian59.Bot.IRC/IRCChatStyle.cs, Meridian59.Bot.IRC/Properties/AssemblyInfo.cs, Meridian59.Bot.IRC/configuration.xml
EsperNET has a ~450 char limit which is lowered by using color/style codes, and messages from the server (i.e. broadcasts) can often be in excess of this (up to 550 IIRC). Split at a conservative point (280 chars) to allow for color codes and send the message to the channel in multiple parts. Also attempt to split at a logical point (whitespace) near 280 chars, to avoid chopping up the IRC color/style codes.
Increment assembly version, update configuration.xml for testing server/channel.
Note: I added the try/catch block with exception logging because we're currently using this as-is, some testing has been done but haven't figured out if there's any rare edge cases not being handled.
=> Split large ServerStrings before sending to IRC channel.

Meridian59.Patcher/DownloadForm.Designer.cs, Meridian59.Patcher/DownloadForm.cs, Meridian59.Patcher/LanguageHandler.cs, Meridian59.Patcher/Meridian59.Patcher.csproj, Meridian59.Patcher/Patcher.cs
- Updater form now centers on screen when created.
- Added textbox which receives info on what is happening (files being
downloaded, failures that don't close the updater).
- Added more information to error messages.
- Added a retry option/dialog box for JSON file download failure, will
attempt to download the file until user cancels it.
- Added German language translations for all info/error messages.
Language switching is based on user's OS language choice and is handled
by the updater itself to avoid requiring a separate dll for
translations.
=> Add more info to updater, German translations.

Meridian59.Patcher/DownloadForm.cs, Meridian59.Patcher/LanguageHandler.cs, Meridian59.Patcher/Patcher.cs, Meridian59.Patcher/Properties/AssemblyInfo.cs, Meridian59.Patcher/patchurl.txt
Added classic client patching to the dotnet patcher. Patcher differentiates between '6-arg classic' and '7-arg classic' - for a short time the classic client passed 6 arguments to club before a 7th was added, very few clients would really be updating this way but better to handle that edge case.
Other misc changes:
- Simplfied the infobox string addition code - calling function now provides the whole string to display.
- Added messagebox after patching finishes stating whether anything was updated. Form needs to be updated prior to this in case it misses the last downloaded bytes.
- Incremented patcher version.
=> Allow .NET patcher to update classic client (split from earlier PR).

Meridian59.Patcher/DownloadForm.Designer.cs
Using FormBorderStyles FixedSingle or Fixed3D causes the right-hand
border of the UI to stick out a few pixels past the title bar. Using
Sizeable instead (the default I guess since it didn't add a property for
it in designer) fixes this issue. Added a minimum size so the UI can't
actually be resized.
The other changes were made by VS when i changed the border, seems
that's the way it wants it laid out.
=> Fix irregular right-harnd border on patcher UI.

Meridian59.Patcher/DownloadForm.cs, Meridian59.Patcher/JsonFileProgress.cs, Meridian59.Patcher/LanguageHandler.cs, Meridian59.Patcher/Meridian59.Patcher.csproj, Meridian59.Patcher/PatchFile.cs, Meridian59.Patcher/PatchFileHashedStatus.cs, Meridian59.Patcher/Patcher.cs, Meridian59.Patcher/UpdateStage.cs, Meridian59.Patcher/Worker.cs
Draft implementation of providing UI feedback on hashing process. Shows num_hashed/total_files and length_hashed/total_length in UI prior to download starting. I added a Thread.Sleep() in Worker in the hashing section so that we can see the hashing part of the UI in testing (otherwise it won't show up at all on my computer).
Added a bool to track the start of downloading in Patcher so that 'starting download' text can be displayed in the form (not sure if there's a better way to track that) and also prevented files from giving the 'downloaded file.ext' text in form if they weren't actually downloaded.
Removed extra form tick after loop - issue with progressbar text was due to requiring Text to be modified prior to the Value assignment.
=> Show scanning/hashing and downloading differently in updater UI.

Meridian59/Data/Models/ClientPatchInfo.cs
Update path details may be sent with or without an / on the end of the
folder, don't add an extra one as it won't work properly with AWS.
=> Handle extra forward slash in URLs from server.

Meridian59.Ogre.Client/UIMail.cpp, Meridian59.Ogre.Client/UINewsGroup.cpp
Checks for 'Re:' and 'Aw:' in titles when replying to a mail or news
post, and doesn't add another one if the original title starts with one.
=> Don't duplicate 'Re:' in news/mail composing.

Meridian59/Files/BGF/BgfBitmap.cs
We were looking at some improvements/new features in the BGF editor, and found when importing multiple images as once that the editor would take an exceptionally long time to generate the frames (37 seconds to add 10 800x800 indexed bmps).
After testing I found that this was mostly due to calls to `Color.ToArgb()` inside the inner loop of `BitmapToPixelData`. It's not clear why this is so slow, as the [code it calls is fairly simple](https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Color.cs,1f25b4614bb23053,references). Obtaining the color values beforehand and storing them in an array reduces the time to load the 10 800x800 test bmps from 37s to 1s.
=> Reduce slow calls in bitmap processing loop.

Meridian59.Patcher/LanguageHandler.cs, Meridian59.Patcher/Patcher.cs
Incorrect formatting to String.Format for these error messages can cause
an exception. Also adjusted error text so players know to close an extra
client if it happens to be open.
=> Fix error text bug in updater.

Meridian59.BgfEditor/Forms/MainForm.Designer.cs, Meridian59.BgfEditor/Forms/MainForm.cs, Meridian59.BgfEditor/ImageLoaderWorker.cs, Meridian59.BgfEditor/Meridian59.BgfEditor.csproj, Meridian59.BgfEditor/Program.cs
Allow loading multiple images at once into the BGF editor. A previous PR increased the speed of loading indexed bitmaps, but loading pngs is still quite slow. Processing them in a queue with 4 worker threads both speeds up loading and prevents the UI being locked while images are loaded.
- Load multiple images at a time into BGF editor.
- Use worker threads to process the images to prevent locking the UI.
- Prevent open/save/new file operation while images are loading.
=> Add threaded multi-image loading in BGF editor.

Meridian59.Ogre.Client/ControllerUI.h, Meridian59.Ogre.Client/UIGuild.cpp, Meridian59/Common/Enums/UserCommandType.cs, Meridian59/Data/DataController.cs, Meridian59/Data/Models/GuildShieldInfo.cs, Meridian59/Data/Models/UserCommand/UserCommand.cs, Meridian59/Data/Models/UserCommand/UserCommandGuildShieldError.cs, Meridian59/Meridian59.csproj
- Disable shield claim button if selected guild shield already belongs
to a guild.
- Add new guild shield error usercommand (UC_GUILD_SHIELD_ERROR) which
sends a ServerString with an error message regarding an attempted guild
shield claim. Use case is displaying the time remaining before a new
shield can be claimed.
=> Guild shield selection changes.

Meridian59.Ogre.Client/UIObjectDetails.cpp, Meridian59.Ogre.Client/UIPlayerDetails.cpp
CEGUI adds an extra \n to the end of editbox text fields, which causes
issues with inscription items (e.g. name change scroll) but also adds
extra space at the end of player descriptions.
Remove extra newline if found for inscriptions, player descriptions and
player homepage strings.
Fixes #282
=> Remove ending newline from editable descriptions/inscriptions.

Meridian59.Ogre.Client/ControllerUI.h, Meridian59.Ogre.Client/DataControllerOgre.cpp, Meridian59.Ogre.Client/DataControllerOgre.h, Meridian59.Ogre.Client/OgreClient.cpp, Meridian59.Ogre.Client/UIAvatarCreateWizard.cpp, Meridian59.Ogre.Client/UIConfirmPopup.cpp, Meridian59.Ogre.Client/UIGuild.cpp, Meridian59.Ogre.Client/UINPCQuestList.cpp, Meridian59.Ogre.Client/UIOptions.cpp, Meridian59.Ogre.Client/UIStatChangeWizard.cpp, Meridian59/Data/DataController.cs
ConfirmPopup windows don't get closed on data invalidation (i.e. system
save) which can cause an issue with stat reset - invalid stat reset data
could be sent to the server even though the stat reset window itself has
been hidden.
This change clears the data in ConfirmPopup and hides it if present when
Invalidate is called and any open ConfirmPopup has the CloseOnInvalidate
bool set to true. Currently set for stat reset, guild, quest and char
create popups.
~~This change clears the data in ConfirmPopup and hides it if present when~~
~~the visible status on the stat reset window changes from visible to~~
~~hidden.~~
~~I think a more elegant way to handle this would be to inform the~~
~~ConfirmPopup window directly from DataController's Invalidate method,~~
~~maybe by having ConfirmPopup …
=> Allow Invalidate to close specific ConfirmPopup windows.

Meridian59.Ogre.Client/ControllerInput.cpp, Meridian59.Ogre.Client/ControllerInput.h, Meridian59.Ogre.Client/OgreListeners.cpp
Catch time of last left click (mouseup) and if another left click comes
within 350ms, register as a left double click and try activate the
current highlighted object (previous click would have selected it).
Allows using mana nodes/levers and looking inside chests with double
click.
Closes #17
=> Allow left double-click to activate targeted object.

Meridian59.Ogre.Client/Constants.h, Meridian59.Ogre.Client/ControllerUI.cpp, Meridian59.Ogre.Client/ControllerUI.h, Meridian59.Ogre.Client/UIObjectDetails.cpp, Meridian59.Ogre.Client/UISkillDetails.cpp, Meridian59.Ogre.Client/UISpellDetails.cpp
Object descriptions (mainly for items) and spell descriptions tend to
force a scrollbar on the inspection window as the window isn't large
enough to display all the text. At the same time, a default larger
window would look strange for short descriptions. This change
dynamically resizes the window so more of the text will fit, from the
current min up to the current max size.
Object inspection windows with inscriptions aren't resized as this is
less of a problem, and the main focus (inscription editbox) on the most
common items with inscriptions already uses the available max space.
Closes #31.
One question about this - instead of calling SetLayout() for a changed
Description in UIObjectDetails.cpp, it could instead check if the object
has an inscription and call Window->setHeight without …
=> Resize MultiLineEditboxes to fit text where possible.

Meridian59.Ogre.Client/ControllerUI.cpp, Meridian59.Ogre.Client/ControllerUI.h, Meridian59.Ogre.Client/OgreClientConfig.cpp, Meridian59.Ogre.Client/OgreClientConfig.h, Meridian59.Ogre.Client/UIActionButtons.cpp, Meridian59.Ogre.Client/UISkills.cpp, Meridian59/Client/BaseClient.cs, Meridian59/Common/Enums/ActionButtonType.cs, Meridian59/Common/Enums/SchoolType.cs, Meridian59/Data/DataController.cs, Meridian59/Data/Lists/SkillList.cs, Meridian59/Data/Lists/SkillObjectList.cs, Meridian59/Data/Models/ActionButtonConfig.cs, Meridian59/Data/Models/ChatCommand/ChatCommand.cs, Meridian59/Data/Models/ChatCommand/ChatCommandPerform.cs, Meridian59/Data/Models/SkillObject.cs, Meridian59/Meridian59.csproj, Meridian59/Protocol/Enums/MessageTypeGameMode.cs, Meridian59/Protocol/GameMessages/GameMode/ReqPerformMessage.cs, Meridian59/Protocol/GameMessages/GameMode/SkillAddMessage.cs, Meridian59/Protocol/GameMessages/GameMode/SkillsMessage.cs, Meridian59/Protocol/MessageController/MessageController.cs, Meridian59/Protocol/MessageEnrichment.cs, Resources/ui/looknfeel/TaharezLook.looknfeel
- Add corelib code for active skills (mirroring how spells are handled in more places).
- Spell and skill removal now remove the ability from the UI lists and SpellObjects/SkillObjects lists, also fixes a bug where spells were not removed from the UI on spell removal server-side (skills worked because the whole list got resent).
- BP_STAT/Stat protocol can now handle addition of a single spell or skill, so the server can send just that one and not the whole list when the player gets an ability added.
- Add a ReqPerform protocol mirroring ReqCast but for (active) skills. Can be triggered using a chat command.
- Skills UI now allows dragging (only) active skills onto the action grid so they can be performed by hotkey. Active skills use the spell icon type to accomplish this, with passive …
=> Framework for active skills, spell + skill addition/removal protocol changes.

Meridian59.Ogre.Client/Constants.h, Meridian59.Ogre.Client/ControllerUI.h, Meridian59.Ogre.Client/UIInventory.cpp, Meridian59/Data/DataController.cs
- Remove default InventoryObjectList size from DataController, allowing
list to resize to contents (important for keeping track of no. items).
- Create inventory grid UI row by row, resizing the grid as needed
(default minimum 6 rows).
- Allow inventory rows to be added or removed as items are added or
removed. No maximum row count set, but won't remove rows below the
default minimum.
Closes #22. I wanted to look at resizable width (dynamic columns)
also but wanted a solid implementation of the rows complete first.
=> Allow dynamic resizing of inventory rows.

Meridian59.Ogre.Client/UIAvatarCreateWizard.cpp
Sliders would lose the 'slider' part due to having their max value set
to 0 when CharCreationInfo was reset. Avoid setting the max value to 0,
and also reset the current slider value to 0 when properties change to
match expected defaults.
Fixes #148, and the bug can be replicated exactly as described in that issue.
=> Fix sliders in char creation UI.

Meridian59.BgfEditor/Forms/AddFrameSetIndexForm.cs, Meridian59.BgfEditor/Forms/MainForm.Designer.cs, Meridian59.BgfEditor/Forms/MainForm.cs, Meridian59.BgfEditor/Forms/MainForm.resx, Meridian59.BgfEditor/Forms/SettingsForm.cs, Meridian59.BgfEditor/Program.cs, Meridian59/Files/BGF/BgfBitmap.cs, Meridian59/Files/BGF/BgfFile.cs
Added an 'ask-to-save' feature, triggered by attempting to close the program, or by opening a new file or storyboard when the current bgf has unsaved changes. User can choose yes/no/cancel with the expected effects. Clicking yes still triggers the 'save as' menu vs automatically overwriting the current file.
Added tooltips to most menu items and buttons to provide more information on usage.
Fix an issue preventing loading xml/bmp data - XmlReader.Create() requires the full file name to load the xml file.
Fix storyboard import not loading the shrink value or bgf name. Several properties need to be set in forms when a file is loaded. Moved these to a new method which can be called when a storyboard is imported successfully.
Fixed a crash caused by an exception in BgfBitmap.Compress(). Found …
=> BGF editor usability improvements and fixes.

Meridian59.Ogre.Client/UIPlayerOverlays.cpp
Always show UI elements (chat box, inventory, spells etc) on top of the 1st person weapon/shield overlays.
Players have requested this change as they'd prefer things like chat/inventory to always show on top of the 1st person overlays. Clicking through the overlay works, but it does block vision of the UI which they deem more important.
=> Show UI elements on top of 1st person overlays.

Meridian59.Ogre.Client/OgreClientConfig.cpp
Saves the BrightnessFactor config option correctly as a parseable float. Important for locales where the decimal point would be `,` rather than `.`.
=> Fix number format handling for brightness.

Meridian59/Data/Models/StatChangeInfo.cs
The existing calculation was correct for simple builds, but breaks down
when characters have multiple schools at level one. Used the server-side
calculations instead.
=> Fix intellect calculations in stat reset.

Meridian59.BgfService/App_Code/FileHttpHandler.cs, Meridian59.BgfService/Global.asax, Meridian59.BgfService/index.html
One functionality missing from BgfService was the ability to send a
group index and obtain a frame from it (as opposed to sending the frame
index). This change adds a group parameter to the file option, allowing:
- file/{name}/group/{group_index}
- file/{name}/group/{group_index}/{angle}
- file/{name}/group/{group_index}/{angle}/{palette}
Added group examples to index.html.
=> Add 'group' parameter to file option in BgfService.

Meridian59/Data/DataController.cs
Effects are being cleared when Invalidate() is called (i.e. during
server save/GC) but this data is not resent from the server afterwards
as it does not involve any object ID changes. This means that a save
will remove visual effects like blind, dazzle & the white-out effect
from phase. Preventing Effects clearing during Invalidate() fixes this.
=> Don't clear effects on data invalidation.
